aquasecurity/fanal

README.md, analyzer/library/cargo/cargo.go, cmd/fanal/main.go, go.mod, go.sum
Support Cargo.lock for Rust.
```
$ go build -o fanal cmd/fanal/main.go
$ docker save trivy-ci-test:latest -o test.tar
$ ./fanal -f test.tar
{Name:3.7.1 Family:alpine}
Packages: 58
node-app/package-lock.json: 13
python-app/Pipfile.lock: 55
ruby-app/Gemfile.lock: 54
rust-app/Cargo.lock: 74
```
=> Support Cargo.lock analyzer

cache/cache.go
When scanning `knqyf263/test-image`, the file name of cache causes an error as the image name is used as the cache path.
=> Replace slash with underscore

README.md, analyzer/library/poetry/poetry.go, cmd/fanal/main.go
```
$ go build -o fanal cmd/fanal/main.go
$ docker save trivy-ci-test:latest -o poetry.tar
$ ./fanal -f poetry.tar
{Name:3.7.1 Family:alpine}
via image Packages: 65
via file Packages: 83
poetry-app/poetry.lock: 11
yarn-app/yarn.lock: 12
ruby-app/Gemfile.lock: 54
rust-app/Cargo.lock: 74
php-app/composer.lock: 14
node-app/package-lock.json: 13
python-app/Pipfile.lock: 55
```
=> Support poetry.lock file 

analyzer/analyzer.go, analyzer/pkg/apk/apk.go, analyzer/pkg/dpkg/dpkg.go, analyzer/pkg/rpm/rpm.go, analyzer/pkg/rpmcmd/rpm.go
My original issue was that I was trying to run `trivy` on a OS X based system on a CentOS based image. I was getting back an "Unknown OS" error even though `trivy` should have considered my image having a known OS. After some debugging, I discovered that all errors were being suppressed from the different package analyzers and that the issue was that the `rpm` command was not locally installed on my system.
Master build run on an RPM based distro:
```bash
./trivy centos:7
2019-06-29T12:32:55.138-0700	INFO	Updating vulnerability database...
2019-06-29T12:32:59.893-0700	FATAL	error in image scan: failed to scan image: failed to analyze OS packages: Unknown OS
```
Branch build run on RPM based distro:
```bash
./trivy centos:7
2019-06-29T12:33:15.886-0700	INFO	Updating vulnerability …
```
=> Improves package analysis errors usability

analyzer/library/composer/composer.go, utils/utils.go
https://github.com/aquasecurity/fanal/issues/33
https://github.com/aquasecurity/trivy/issues/147
before
```
data/vendor/simplesamlphp/simplesamlphp/modules/mfa/composer.lock: 38
root/.composer/composer.lock: 1
data/vendor/silinternational/psr3-adapters/composer.lock: 2
data/vendor/silinternational/ssp-utilities/composer.lock: 6
data/vendor/simplesamlphp/simplesamlphp/composer.lock: 24
data/vendor/simplesamlphp/simplesamlphp/modules/sildisco/composer.lock: 36
root/.composer/vendor/fxp/composer-asset-plugin/composer.lock: 0
data/vendor/simplesamlphp/simplesamlphp/modules/profilereview/composer.lock: 29
data/vendor/simplesamlphp/simplesamlphp/modules/silauth/composer.lock: 57
data/vendor/simplesamlphp/simplesamlphp/modules/sildisco/development/browser_test/composer.lock: 0 …
```
=> skip scan composer.lock in vendor dir

analyzer/pkg/dpkg/dpkg.go, extractor/docker/docker.go, extractor/docker/docker_test.go
fix for https://github.com/aquasecurity/trivy/issues/96 (https://github.com/aquasecurity/fanal/issues/28)
```
$ go run cmd/fanal/main.go gcr.io/distroless/java:11
{Name:9.9 Family:debian}
via image Packages: 19
via file Packages: 0
$ go run cmd/fanal/main.go debian:latest
{Name:10.0 Family:debian}
via image Packages: 91
via file Packages: 0
```
=> extract all files in target require filedirs

analyzer/analyzer.go
Fix a bug from #35. Even if err is nil, it is wrapped.
=> Bug fix: wrap nil err

analyzer/pkg/rpm/rpm.go, analyzer/pkg/rpmcmd/rpm.go, extractor/docker/docker.go
Fix #29 
If `RequiredFiles()` contains a directory (which has a slash at the end), it always breaks the loop and can't extract files correctly.
=> Fix wrong break

analyzer/library/composer/composer.go, analyzer/library/const.go, analyzer/library/npm/npm.go, analyzer/library/yarn/yarn.go, extractor/docker/docker.go, extractor/docker/docker_test.go, utils/utils.go
fanal ignores `package-lock.json` under `node_modules` dir and composer.lock under `vendor` dir. But, composer.lock may rarely be under `node_modules`.
https://github.com/aquasecurity/trivy/issues/179#issuecomment-547413735
So, I think fanal should ignore all files under `node_modules` and `vendor` directory.
=> feat(library): ignore files under vendor dir

analyzer/analyzer.go
Workaround for a deficient Ping implementation of reg package.
Ping fails on docker registries that return http 401
Authentication Required when requesting general /v2 url, but
happily allow unauthenticated pull of a specific image.
If there is any benefit of having Ping() enabled, it's not apparent.
Especially comparing it with how many registries are unusable with it.
Closes aquasecurity/trivy#229
Signed-off-by: Jakub Bielecki <jakub.bielecki@codilime.com>
=> fix docker reg with option SkipPing

extractor/docker/token/ecr/ecr.go, types/docker.go
AWS SDK sometime needs session token when authorize it.
i.e.) https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html
=> add aws session token

analyzer/analyzer.go, analyzer/analyzer_test.go, cache/cache_test.go, extractor/docker/docker.go, extractor/docker/docker_test.go, types/image.go
Currently, we handle the ID of a layer as single `LayerID`, but there are two types of ID, `Digest` and `DiffID`.
`DiffID` is mainly used in Docker Engine.
https://github.com/moby/moby/blob/master/image/spec/v1.2.md#terminology
`Digest` is used in Docker Registry.
https://docs.docker.com/registry/spec/manifest-v2-2/#manifest-list-field-descriptions
Their difference between them is whether the layer is compressed. I thought that it would be better for the future to handle them separately.
=> feat: split LayerID into Digest and DiffID

.github/workflows/bench.yml, integration/benchmark_test.go
Currently, our benchmark measures only `Analyze()` function, but this PR also measures the initialize cost of each struct. We're working on replacing containers/image with google/go-containerregistry now. I found `containers/image` did most of the processes in the constructor, while google/go-containerregistry did them after the constructor. It means containers/image looks faster than google/go-containerregistry in our benchmark.
Also, this PR makes the benchmark look worse because it includes the initial cost now. So, I skip the test once.
=> fix(bench): measure initializing structs

analyzer/analyzer.go, analyzer/analyzer_test.go, cmd/fanal/main.go
We should send back package and apps info if found even
in the case of an unknown OS. Example Dockerfile:
```
$ cat Dockerfile
FROM hello-world
ADD https://raw.githubusercontent.com/aquasecurity/trivy-ci-test/master/Cargo.lock .
```
Should say ErrUnknownOS but still scan the Cargo vulns.
Addresses: https://github.com/aquasecurity/trivy/pull/470
Signed-off-by: Simarpreet Singh <simar@linux.com>
=> analyzer: Send back package and apps info for unknown OS if found.

image/daemon/image.go
Ensure that the client and file is closed either in error cases or once cleanup() is called so no file descriptors are leaked.
If ImageInspectWithRaw
https://github.com/aquasecurity/fanal/blob/1b5f79c38073afe1a11ee19fe1f1095535dc6ce8/image/daemon/image.go#L42
fails the docker client is not closed, and thus will leak filedescriptors to the underlying network connection to docker.
This happens when you reuse the fanal code in a long-running process.
Unfortunately I don't know of a good automated test case, it can be tested by shelling out to lsof to count open files, e.g. in
https://github.com/aquasecurity/fanal/blob/master/image/image_test.go
Example Test
```go
func countOpenFiles() int {
out, err := exec.Command("/bin/sh", "-c", fmt.Sprintf("lsof -p %v", os.Getpid())).Output()
if err != …
```
=> Close open connections and files

analyzer/library/const.go, analyzer/library/nuget/nuget.go, go.mod, go.sum
This pull requests include a new analyzer for NuGet `packages.lock.json` files.  
It's basically the same as the other analyzers, but makes use of the NuGet parser which is included in the following `go-dep-parser` [pull request](https://github.com/aquasecurity/go-dep-parser/pull/14).
For reference, feature request issue can be found here: https://github.com/aquasecurity/trivy/issues/681
=> Feat: Created analyzer for NuGet lockfiles.

go.mod, go.sum
- https://github.com/aquasecurity/trivy/issues/1004
- https://github.com/aquasecurity/go-dep-parser/pull/33
It works with `quay.io/eclipse/che-plugin-sidecar@sha256:8615a29435b0256bffaf85ab2cf9327b059f14eaa6614346dfd51e3a6dd9f041` now.
```
$ ./fanal image quay.io/eclipse/che-plugin-sidecar@sha256:8615a29435b0256bffaf85ab2cf9327b059f14eaa6614346dfd51e3a6dd9f041
quay.io/eclipse/che-plugin-sidecar@sha256:8615a29435b0256bffaf85ab2cf9327b059f14eaa6614346dfd51e3a6dd9f041
RepoTags: []
RepoDigests: [quay.io/eclipse/che-plugin-sidecar@sha256:8615a29435b0256bffaf85ab2cf9327b059f14eaa6614346dfd51e3a6dd9f041]
&{Family:debian Name:9.13}
via image Packages: 188
gomod (usr/local/go/src/cmd/go.sum): 12
gomod (usr/local/go/src/go.sum): 5
gobinary (usr/local/go/bin/golangci-lint): 71
gobinary …
```
=> fix(gomod): fix a panic

artifact/image/image.go, artifact/image/image_test.go
We should not scan go.sum in container images, only scan go binaries because there may be go.sum in the container image that are not actually being used.
There are noisy go.sum files in the container image.
```
docker run --rm -it quay.io/eclipse/che-plugin-sidecar@sha256:8615a29435b0256bffaf85ab2cf9327b059f14eaa6614346dfd51e3a6dd9f041 bash
root@9434b607f1bc:/go# find / -name go.sum
/usr/local/go/src/cmd/go.sum
/usr/local/go/src/go.sum
/go/src/golang.org/x/mod/go.sum
/go/src/golang.org/x/tools/gopls/go.sum
/go/src/golang.org/x/tools/go.sum
/go/src/golang.org/x/lint/go.sum
/go/src/golang.org/x/net/go.sum
/go/src/golang.org/x/net/http2/h2demo/go.sum
/go/src/github.com/cweill/gotests/go.sum
/go/src/github.com/karrick/godirwalk/examples/find-fast/go.sum …
```
=> fix(image): disable go.sum scanning

image/token/google/google.go, image/token/google/google_test.go, image/token/token.go
This commit adds the capability to scan images from Google artifact
registry(GAR). GAR domains were earlier rejected by Trivy e.g.
europe-west3-docker.pkg.dev etc. With this change, we will treat domain
ending with 'docker.pkg.dev' as GAR domain and use gcloud sdk to fetch
credentials from provided file or credstore.
=> feat: Support Google artifact registry

cmd/fanal/main.go, policy/engine.go, policy/testdata/combine/combined_deployment.rego, policy/testdata/combine/combined_docker.rego, policy/testdata/combine/combined_pod.rego, policy/testdata/combine/deployment.rego, policy/testdata/combine_exception/combined_deployment.rego, policy/testdata/combine_exception/deployment.rego, policy/testdata/combine_exception/exceptions.rego, policy/testdata/combine_exception/fail.rego, policy/testdata/happy/deployment.rego, policy/testdata/happy/docker.rego, policy/testdata/happy/pod.rego, policy/testdata/namespace_exception/100.rego, policy/testdata/namespace_exception/200.rego, policy/testdata/namespace_exception/exceptions.rego, policy/testdata/rule_exception/deployment.rego, policy/testdata/sad/broken_metadata.rego, policy/testdata/sad/broken_msg.rego, policy/testdata/sad/broken_rule.rego, policy/testdata/sad/missing_filepath.rego, policy/testdata/sad/missing_metadata.rego, policy/testdata/sad/missing_metadata_fields.rego, types/misconf.go, utils/utils.go
Before:
```
__rego_input__ := {
"combine": true,
"selector": {"types": ["kubernetes"]},
}
```
After:
```
__rego_input__ := {
"combine": true,
"selector": [{"type": "kubernetes"}],
}
```
=> fix(config): change selector type

analyzer/language/python/packaging/packaging.go, analyzer/language/python/packaging/packaging_test.go
Python Eggs has two formats
- .egg format
- .egg-info format
Currently, fanal supports only `.egg-info` format. This PR adds support of `.egg` directory format. `.egg` file will be supported in another PR.
https://setuptools.readthedocs.io/en/latest/deprecated/python_eggs.html#eggs-and-their-formats
=> feat(python): support .egg directory format

image/daemon/image.go, image/daemon/image_test.go, image/image_test.go
The OS Name collected from docker inspect will be set to v1.ConfigFile.OS. 
This avoid empty value for OS field.
=> fix(configfile-OS): Enriched config file metadata with OS value

analyzer/language/golang/binary/binary.go
Add skipping large files whose size is more than 200MB.
Fixes [aquasecurity/trivy#1242](https://github.com/aquasecurity/trivy/issues/1242)
=> fix(go-binary): skip large files

analyzer/pkg/rpm/rpm.go, analyzer/pkg/rpm/rpm_test.go
https://github.com/aquasecurity/trivy/issues/1172  
Fixes #212
Before:
```
panic: runtime error: slice bounds out of range [:-1]
goroutine 2306 [running]:
github.com/aquasecurity/fanal/analyzer/pkg/rpm.splitFileName(0xc00004ad80, 0x1a, 0x50, 0xc002347000, 0x50, 0x50, 0xc0006bdc2f, 0x6)
/go/src/github.com/aquasecurity/fanal/analyzer/pkg/rpm/rpm.go:133 +0x1f1
github.cogor/pkg/rpm.rpmPkgAnalyzer.parsePkgInfo(0xc00b75c000, 0x1211000, 0x1530000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/aquasecurity/fanal/analyzer/pkg/rpm/rpm.go:87 +0xb17
github.cogor/pkg/rpm.rpmPkgAnalyzer.Analyze(0x0, 0x0, 0xc002f194d0, 0x14, 0xc00b75c000, 0x1211000, 0x1530000, 0x2, 0xc009c6e4e0, 0x11eaeda)
/go/src/github.com/aquasecurity/fanal/analyzer/pkg/rpm/rpm.go:31 +0x5a …
```
=> fix(rpm): don't panic when parse source rpm name failed

analyzer/config/yaml/testdata/incompatible_json.yaml, analyzer/config/yaml/yaml_test.go, config/parser/yaml/yaml.go, config/parser/yaml/yaml_test.go, go.mod, go.sum
https://github.com/aquasecurity/trivy/issues/1251
https://github.com/aquasecurity/trivy/issues/1183
root cause: https://github.com/go-yaml/yaml/issues/139
=> fix(config/yaml): support yaml files which incompatible with json spec

image/daemon/image.go
It is possible that `Config` is nil and it causes panic.
```
docker inspect registry.redhat.io/rhel7:7.0-27                                                                                   [~/src/github.com/aquasecurity/fanal]
[
{
"Id": "sha256:bc668af2b27f909aa48aeb12194483bdf165e44b4879c7b89b39c75f48d6fa0f",
"RepoTags": [
"registry.redhat.io/rhel7:7.0-27"
],
"RepoDigests": [
"registry.redhat.io/rhel7@sha256:489b7ba5ed0c9f63d85fd94b990f52b719f2bde006a0df168d2999fc771e5cca"
],
"Parent": "",
"Comment": "Created by Image Factory",
"Created": "2015-02-10T09:12:45Z",
"Container": "",
"ContainerConfig": {
"Hostname": "",
"Domainname": "",
"User": "",
"AttachStdin": false,
"AttachStdout": false,
"AttachStderr": false,
"Tty": false,
"OpenStdin": false,
"StdinOnce": false,
"Env": null,
"Cmd": …
```
=> fix(daemon): handle nil config

go.mod, go.sum
Updating go-dep-parser dependency to include fix for issue #323
=> chore: update go-dep-parser dependency to fix pip parsing issue

artifact/artifact.go, artifact/remote/git.go, artifact/remote/git_test.go
Hi,
this is my proposal to support #334 which is needed to fix trivy issue [928](https://ghttps://github.com/aquasecurity/trivy/issues/927ithub.com/aquasecurity/trivy/issues/927).
Given the current architecture I found it easiest to extend the artifact options for this use case even tough the option probably doesn't fit a 100 % in there.
Any feedback is much appreciated.
=> allow suppressing the git clone output by setting the quiet option

go.sum
There were removed several old dependencies after `go mod tidy`.
=> chore: removed old `tfsec` dependencies.

artifact/local/fs.go, artifact/local/fs_test.go
Closes [trivy issue1479](https://github.com/aquasecurity/trivy/issues/1479)
=> fix: fixed skipFiles/skipDirs flags for relative path

analyzer/pkg/rpm/rpm.go, go.mod, go.sum, test/integration/library_test.go, test/integration/testdata/goldens/packages/suse-sle15-15.3.17.8.16.json.golden
RPM databases in the native DB format rather than the traditional
Berkeley DB format are stored as different filenames, so detect
those as well.
(This needs a rebase on top of a newer version of go-rpmdb when https://github.com/knqyf263/go-rpmdb/pull/9 is merged)
Fix https://github.com/aquasecurity/fanal/issues/183
=> Also detect RPM databases in NDB format (Fixes #183)

analyzer/language/java/pom/pom_test.go, analyzer/language/java/pom/testdata/requirements/pom.xml, go.mod, go.sum
Ignore unsupported requirements such as `(,1.0]`.
```
<dependency>
<groupId>com.fasterxml.jackson.dataformat</groupId>
<artifactId>jackson-dataformat-xml</artifactId>
<version>(,2.8.0]</version>
</dependency>
```
=> fix(java/pom): ignore unsupported requirements

analyzer/pkg/rpm/rpm.go
Added checking of rpm packages for being provided by OS vendor. 
- aquasecurity/trivy/issues/1546
- aquasecurity/trivy/issues/1481
=> fix(rpm): do not ignore installed files via third-party rpm

artifact/artifact.go, artifact/remote/git.go, artifact/remote/git_test.go
In trivy/fanal
- quiet: means no any output including log messages
- no-progress: disable progress bar
So, no progress is better here.
=> refactor: rename quiet with no progress

.github/dependabot.yml
We tried running Dependabot weekly for a while, but it was a bit noisy. This PR changes the interval to monthly.
=> chore(dependabot): set interval to monthly

hook/filter/filter.go, hook/filter/filter_test.go
When scanning Amazonlinux or CentOS rootfs directory, RPM has SystemFile ="/". After trimming the "/" prefix, we have an empty SystemFile.
The filePath of some file libraries is empty. These libraries [will be removed](https://github.com/aquasecurity/fanal/blob/e8f5ba7a5e5e4ae4b4c05a9b2d1c554151e1fd58/hook/filter/filter.go#L64-L66).
1. Run docker container amazonlinux:2. 
2. Install `helmfile`
```
curl -LO https://github.com/roboll/helmfile/releases/download/v0.141.0/helmfile_linux_amd64 &&
mv helmfile_linux_amd64 /usr/local/bin/helmfile &&
chmod +x /usr/local/bin/helmfile
```
3. Start `trivy -d rootfs /`
4. Trivy [finds](https://github.com/aquasecurity/fanal/blob/e8f5ba7a5e5e4ae4b4c05a9b2d1c554151e1fd58/analyzer/pkg/rpm/rpm.go#L98) `helmfile` gobinary application:
``` …
```
=> fix(hook): fix skip of language-specific files when scanning rootfs directory

go.mod, go.sum
Update `go-dep-parser` for correct handling a package name with a hyphen
=> fix(deps): correct handling a package name with a hyphen

go.mod, go.sum
Update go-dep-parser so that it fixes a Maven bug.
https://github.com/aquasecurity/trivy/issues/1728
https://github.com/aquasecurity/go-dep-parser/pull/83
=> fix(pom): keep an order of dependencies

hook/filter/filter.go, hook/filter/filter_test.go
Currently Filter hook filters systemfiles resources from Applications and Packages.
Updated the hook to filter CustomResources as well.
=> fix(filter-hook): systemfiles filter for custom resources

go.mod, go.sum
BurntSushi/toml@v1.0.0 contained a test with a critical error causing a panic. 
v1.1.0 fixes it.
=> chore(deps): update BurntSushi/toml for fix runtime error

go.mod, go.sum
Scanning of some cloudformation files caused panic due to out of range. 
it was fixed in `defsec`: https://github.com/aquasecurity/defsec/pull/516/files
=> fix(deps): correct margin removal for empty lines inside cloudformation files

analyzer/secret/secret_test.go, secret/scanner.go, secret/scanner_test.go
The secret scanning doesn't support multi-lines at the moment. The end line number should be the same as the start line number.
=> fix(secret): end line number is the same as start line number

hook/gomod/gomod.go, hook/gomod/gomod_test.go
A nil pointer dereference occurs when go.sum is not found.
- go.mod
```
module github.com/org/repo
go 1.16
require github.com/aquasecurity/go-dep-parser v0.0.0-20211224170007-df43bca6b6ff
require gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b // indirect
```
```console
$ fanal fs go.mod
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x171b959]
goroutine 1 [running]:
github.com/aquasecurity/fanal/hook/gomod.mergeGoSum(...)
/home/mainek00n/github/github.com/MaineK00n/fanal/hook/gomod/gomod.go:83
github.com/aquasecurity/fanal/hook/gomod.gomodMergeHook.Hook({}, 0xc00083ee00)
/home/mainek00n/github/github.com/MaineK00n/fanal/hook/gomod/gomod.go:36 +0x479 …
```
=> fix(hook/gomod): check if gosum is nil

cache/redis.go, cache/redis_test.go, cmd/fanal/main.go
By default, fanal uses BoltDB for cache backend. It contains only JSON and should not be such a big size. But just in case scanning a lot of images, it would be nice to support TTL in Redis.
=> feat(redis): support TTL

go.mod, go.sum
[defsec](https://github.com/aquasecurity/defsec) contained `x/crypto` with  CVE-2022-27191.
it was update here: https://github.com/aquasecurity/defsec/pull/526
this PR updates `defsec`.
before:
```sh
$ trivy fs --skip-dirs test/ . | grep CVE-2022-27191
| golang.org/x/crypto                  | CVE-2022-27191   | HIGH     | 0.0.0-20220208233918-bba287dce954   | 0.0.0-20220315160706-3147a52a75dd | golang: crash in a                    |
```
after:
```sh
$ trivy fs --skip-dirs test/ . | grep CVE-2022-27191
$
```
=> chore(deps): update defsec for fix CVE-2022-27191 inside x/crypto

secret/builtin-allow-rules.go, secret/scanner.go, secret/scanner_test.go, secret/testdata/allow-regex-outside-group.yaml
When using the secret-group-name feature, the match we check the allow-list-rules on is the secret-group itself.
This behavior is unexpected and causes more false positives.
Changed to match the whole regex match for allow-rules, not only the secret-group.
=> refactor(secret): allow list match with secret subgroups

go.mod, go.sum
Relates to https://github.com/aquasecurity/trivy/issues/2141
Signed-off-by: Liam Galvin <liam.galvin@aquasec.com>
=> chore(deps): Update defsec to v0.58.0

go.mod, go.sum
See https://github.com/aquasecurity/defsec/pull/612
Signed-off-by: Liam Galvin <liam.galvin@aquasec.com>
=> chore(deps): Update defsec to v0.58.2 (fixes false positives in ksv038)
