- analyzer/analyzer.go
- cmd/fanal/main.go
- extractor/docker.go
- go.sum
Use local images when docker daemon exists in the local machine.
If not, fanal will download image layers from a remote repository.
> Use local images when docker daemon exists

- README.md
- extractor/docker.go
Depending on images, `docker save` takes a minute.
Cache the saved image.
> Cache the saved image

- analyzer/library/npm/npm.go
- analyzer/library/yarn/yarn.go
- cmd/fanal/main.go
- go.mod
- go.sum
- utils/utils.go
> add yarn.lock parser

- analyzer/pkg/apk/apk.go
- analyzer/pkg/dpkg/dpkg.go
- go.mod
- go.sum
> Use go-deb-version for version validation

- analyzer/analyzer.go
> to be able add required files

- extractor/docker/docker.go
- extractor/extractor.go
Fix: https://github.com/aquasecurity/fanal/issues/30
> Change error log for ErrCouldNotExtract

- analyzer/analyzer.go
- analyzer/command/apk/apk.go
- analyzer/os/common.go
- analyzer/os/redhatbase/redhatbase.go
- analyzer/pkg/apk/apk.go
- analyzer/pkg/apk/apk_test.go
- analyzer/pkg/rpm/rpm.go
- analyzer/pkg/rpmcmd/rpm.go
- extractor/docker/docker.go
- extractor/docker/token/gcr/gcr.go
Add error wrap for the easy-to-understand error message.
> Add error wrap

- analyzer/pkg/rpmcmd/rpm.go
- types/error.go
- utils/utils.go
For an easy-to-understand message
https://github.com/aquasecurity/trivy/issues/156
> Check whether rpm is installed

- cache/cache.go
- cache/cache_test.go
- cmd/fanal/main.go
- extractor/docker/docker_test.go
- go.mod
Adds some unit tests for cache.go
Signed-off-by: Simarpreet Singh <simar@linux.com>
> Add cache tests

- extractor/image/token.go
- extractor/image/token_test.go
> fix(token): use the credential from enviroment variable

- analyzer/command/apk/apk.go
> Support settings apkIndexArchiveURL via env FANAL_APK_INDEX_ARCHIVE_URL

- cache/s3.go
- cache/s3_test.go
> fix(s3/cache): HeadObject bucketName was missing.

- analyzer/pkg/apk/apk.go
- analyzer/pkg/apk/apk_test.go
- analyzer/pkg/apk/testdata/apk
- go.mod
- go.sum
Use https://github.com/knqyf263/go-apk-version
> fix(apk): replace go-deb-version with go-apk-version

- analyzer/pkg/dpkg/dpkg.go
- analyzer/pkg/dpkg/testdata/dpkg
[Issue](https://github.com/aquasecurity/fanal/issues/126)
> Check status for dpkg package

- image/image.go
ref. https://github.com/aquasecurity/fanal/pull/130
> refactor(image): minor changes

- cmd/fanal/main.go
Forgot to import `nuget` in `main.go`.
https://github.com/aquasecurity/fanal/pull/139
> fix(main): import nuget

- analyzer/pkg/rpm/rpm.go
- cmd/fanal/main.go
- go.mod
- go.sum
Update go-rpmdb to remove C-bindings
https://github.com/knqyf263/go-rpmdb/pull/3
> feat: remove CGO

- analyzer/config/const.go
- analyzer/config/toml/testdata/broken.toml
- analyzer/config/toml/testdata/deployment.toml
- analyzer/config/toml/toml.go
- analyzer/config/toml/toml_test.go
- analyzer/const.go
https://github.com/aquasecurity/trivy/issues/834
> feat(config): support TOML files

- analyzer/config/const.go
- analyzer/config/json/json.go
- analyzer/config/json/json_test.go
- analyzer/config/json/testdata/array.json
- analyzer/config/json/testdata/broken.json
- analyzer/config/json/testdata/deployment.json
- analyzer/const.go
https://github.com/aquasecurity/trivy/issues/834
> feat(config): support JSON files

- analyzer/library/nuget/nuget_test.go
https://github.com/aquasecurity/fanal/pull/228
> test(nuget): sort libraries for consistency

- analyzer/analyzer.go
- analyzer/analyzer_test.go
- analyzer/language/python/packaging/packaging.go
- analyzer/language/python/packaging/packaging_test.go
- analyzer/pkg/apk/apk.go
- artifact/image/image.go
- artifact/image/image_test.go
- artifact/local/fs.go
- artifact/local/fs_test.go
- artifact/remote/git.go
- artifact/remote/git_test.go
- cache/key.go
- cache/key_test.go
- cmd/fanal/main.go
- external/config_scan.go
- hook/all/import.go
- hook/hook.go
- hook/hook_test.go
- hook/python/python.go
- hook/types.go
- test/integration/library_test.go
- test/integration/registry_test.go
- types/artifact.go
Hooks are called after analysis so that separate results from each analyzer can be aggregated or processed together.
> feat: add hooks

- analyzer/analyzer_test.go
- analyzer/pkg/apk/apk.go
- analyzer/pkg/apk/apk_test.go
- artifact/image/image.go
- artifact/image/image_test.go
- artifact/local/fs.go
- artifact/local/fs_test.go
- artifact/remote/git_test.go
Extract installed files from `/lib/apk/db/installed`.
- #263
- #265
> feat(apk): analyze installed files

- analyzer/const.go
https://github.com/aquasecurity/trivy/pull/1191
> feat(analyzer): add group consts

- image/daemon/image.go
- image/daemon/image_test.go
- image/image_test.go
> feat(daemon): add more config fields

- analyzer/const.go
- artifact/image/image.go
- artifact/image/image_test.go
- artifact/remote/git.go
- test/integration/testdata/goldens/vuln-image1.2.3.expectedlibs.golden
The disabled analyzers should be passed from outside rather than having default disabled analyzers in fanal.
> fix(artifact): remove default disabled analyzers

- analyzer/config/cloudformation/cloudformation.go
- analyzer/config/cloudformation/cloudformation_test.go
- analyzer/config/config.go
- analyzer/const.go
- artifact/image/image_test.go
- artifact/local/fs_test.go
- artifact/remote/git_test.go
- config/scanner/scanner.go
- config/scanner/scanner_test.go
- config/scanner/testdata/cloudformation.yaml
- go.mod
- go.sum
- CFSec integration to scan config files that are typed as Cloudformation
- add test cases as per terraform ones
> add support for cfsec

- config/scanner/scanner_test.go
- go.mod
- go.sum
- cfsec now has the resource name in the message for the issue
> chore(deps): Bump cfsec version from v0.0.6 to v0.0.7

- applier/docker.go
- applier/docker_test.go
Closes  [trivy issue #1407](https://github.com/aquasecurity/trivy/issues/1407)
> fix(applier): fixed layer applications update

- .github/workflows/test.yml
- .golangci.yml
Hi! I have set up golangci-lint-action. I also disabled several linters that where failing. You can re-enable them when you agree with them and they are fixed.
> ci(lint) : setup golangci-lint-action

- config/scanner/scanner.go
- go.mod
- go.sum
- Update the tfsec version
- Pass debug through to tfsec
> chore(deps): Update tfsec version

- analyzer/config/hcl/hcl_test.go
- config/parser/hcl2/hcl2_test.go
- go.mod
- go.sum
Close https://github.com/aquasecurity/fanal/pull/368
> chore(deps): update hcl2json dependency

- applier/applier_test.go
- applier/docker.go
- artifact/image/image.go
With addition for analyzer group, a CustomResource identifier is added to support any custom analyzer.
This commit allows merging of custom resources
> fix(applier): Modify apply layer to merge custom resources as well

- go.mod
- go.sum
update hcl2json@v0.3.3 -> 0.3.4
> fix(hcl2json): fix panic in hcl2json

- go.mod
- go.sum
Updating defsec and tfsec to address NPE issue in Trivy
> chore(deps): update tfsec and defsec

- analyzer/language/golang/binary/binary_test.go
- go.mod
- go.sum
https://github.com/aquasecurity/go-dep-parser/pull/87
> refactor(golang): use debug/buildinfo

- go.mod
- go.sum
See https://github.com/aquasecurity/trivy/issues/1941 and https://github.com/aquasecurity/trivy/issues/1816
Signed-off-by: Liam Galvin <liam.galvin@aquasec.com>
> fix(iac): Added missing metadata to resolve Terraform scanning errors

- go.mod
- go.sum
I'm on the way to fix https://github.com/aquasecurity/trivy/issues/1943
I recently add a fix in go-dep-parser https://github.com/aquasecurity/go-dep-parser/pull/91
See also https://github.com/aquasecurity/go-dep-parser/pull/91#issuecomment-1089940743
> fix(pom): merge multiple pom imports in a good manner

- analyzer/config/docker/docker.go
> Add Containerfile to requiredFiles

- hook/filter/filter.go
- hook/filter/filter_test.go
Close https://github.com/aquasecurity/trivy/issues/2012
> feat(hook): skip system installed Go binaries

- go.mod
- go.sum
See aquasecurity/go-dep-parser#97
> fix(go): fixed panic for gomod without version

- analyzer/const.go
added array of config file analysers.
This array will be used to disable these analysers.
> refactor(analyzer): added array of config file analysers

- artifact/image/image.go
- artifact/local/fs.go
- artifact/remote/git_test.go
- external/config_scan_test.go
- handler/all/import.go
Regression of https://github.com/aquasecurity/fanal/pull/460
> fix(handler): import go mod handler

- artifact/local/fs_test.go
- go.mod
- go.sum
- fix: update defsec and fix tests accordingly
> chore(deps): latest defsec for Highlight code ommission

- go.mod
- go.sum
Signed-off-by: Liam Galvin <liam.galvin@aquasec.com>
> perf(misconf): Update defsec to v0.58.1 to optimise result creation for very large files

- analyzer/language/analyze.go
- test/integration/library_test.go
- test/integration/testdata/goldens/vuln-image1.2.3.expectedlibs.golden
- types/artifact.go
moving dependencies into packages
> refactor(deps): move dependencies to package

- types/artifact.go
related: https://github.com/aquasecurity/trivy/pull/2203
Ref member added to propagate which PackageURL the vulnerability was detected from.
> feat(types): add Ref to package

- go.mod
- go.sum
- test/integration/testdata/goldens/vuln-image1.2.3.expectedlibs.golden
Update the Indirect field if it's not in the Package dependencies from lock.file
> feat(npm): calculate indirect libraries

- go.mod
- go.sum
- handler/misconf/misconf.go
- types/const.go
Signed-off-by: chenk <hen.keinan@gmail.com>
support rbac scanner and type - solve #562
> feat: support rbac scanner and type

- go.mod
- go.sum
Signed-off-by: chenk <hen.keinan@gmail.com>
bump defsec version v0.68.1
> chore: bump defsec version v0.68.1
